//注入路由引擎
app.config(['$stateProvider','$urlRouterProvider',function($stateProvider,$urlRouterProvider){
	//声明默认导航
	$urlRouterProvider.when('','/index');
	$stateProvider.state('index',{
		url:'/index',
		templateUrl:'view/index.html',
		controller:'indexCtrl'
	})
    //头条
	.state('toutiao',{
		url:'/toutiao',
		templateUrl:'view/toutiao.html',
		controller:'toutiaoCtrl'
	})
	.state('toutiao.tuijian',{
		url:'/tuijian',
		templateUrl:'view/tuijian.html',
		controller:'tuijianCtrl'
	}).state('toutiao.shehui',{
		url:'/shehui',
		templateUrl:'view/shehui.html',
		controller:'shehuiCtrl'
	}).state('toutiao.gaoxiao',{
		url:'/gaoxiao',
		templateUrl:'view/gaoxiao.html',
		controller:'gaoxiaoCtrl'
	}).state('toutiao.qiwen',{
		url:'/qiwen',
		templateUrl:'view/qiwen.html',
		controller:'qiwenCtrl'
	}).state('toutiao.lizhi',{
		url:'/lizhi',
		templateUrl:'view/lizhi.html',
		controller:'lizhiCtrl'
	}).state('toutiao.yangsheng',{
		url:'/yangsheng',
		templateUrl:'view/yangsheng.html',
		controller:'yangshengCtrl'
	}).state('toutiao.yulue',{
		url:'/yulue',
		templateUrl:'view/yulue.html',
		controller:'yulueCtrl'
	}).state('toutiao.keji',{
		url:'/keji',
		templateUrl:'view/keji.html',
		controller:'kejiCtrl'
	}).state('toutiao.baike',{
		url:'/baike',
		templateUrl:'view/baike.html',
		controller:'baikeCtrl'
	}).state('toutiao.caijing',{
		url:'/caijing',
		templateUrl:'view/caijing.html',
		controller:'caijingCtrl'
	}).state('toutiao.qiche',{
		url:'/qiche',
		templateUrl:'view/qiche.html',
		controller:'qicheCtrl'
	}).state('toutiao.qinggan',{
		url:'/qinggan',
		templateUrl:'view/qinggan.html',
		controller:'qingganCtrl'
	}).state('toutiao.xingzuo',{
		url:'/xingzuo',
		templateUrl:'view/xingzuo.html',
		controller:'xingzuoCtrl'
	}).state('toutiao.meishi',{
		url:'/meishi',
		templateUrl:'view/meishi.html',
		controller:'meishiCtrl'
	}).state('toutiao.shishang',{
		url:'/shishang',
		templateUrl:'view/shishang.html',
		controller:'shishangCtrl'
	}).state('toutiao.luyou',{
		url:'/luyou',
		templateUrl:'view/luyou.html',
		controller:'luyouCtrl'
	}).state('toutiao.yuer',{
		url:'/yuer',
		templateUrl:'view/yuer.html',
		controller:'yuerCtrl'
	}).state('toutiao.tiyu',{
		url:'/tiyu',
		templateUrl:'view/tiyu.html',
		controller:'tiyuCtrl'
	}).state('toutiao.junshi',{
		url:'/junshi',
		templateUrl:'view/junshi.html',
		controller:'junshiCtrl'
	})
	//视频
	.state('shipin',{
		url:'/shipin',
		templateUrl:'view/shipin.html',
		controller:'shipinAppCtrl'
	}).state('shipin.dazahui',{
		url:'/dazahui',
		templateUrl:'view/dazahui.html',
		controller:'dazahuiCtrl'
	}).state('shipin.xiaofantian',{
		url:'/xiaofantian',
		templateUrl:'view/xiaofantian.html',
		controller:'xiaofantianCtrl'
	}).state('shipin.qipashi',{
		url:'/qipashi',
		templateUrl:'view/qipashi.html',
		controller:'qipashiCtrl'
	}).state('shipin.yuluequan',{
		url:'/yuluequan',
		templateUrl:'view/yuluequan.html',
		controller:'yuluequanCtrl'
	}).state('shipin.youximi',{
		url:'/youximi',
		templateUrl:'view/youximi.html',
		controller:'youximiCtrl'
	})
	//我的登录注册
	.state('mine',{
		url:'/mine',
		templateUrl:'view/mine.html',
		controller:'mineAppCtrl'
	})
	
//	.state('littleApp.oil',{
//		url:'/oil',
//		templateUrl:'view/oil.html',
//		controller:'oilCtrl'
//	})
}]);